### ISSUE TITLE
Multi File Components Not Mounting

### ISSUE THREAD

**Issue by Gregoyle** [eddyerburgh/vue-test-utils-ava-example#3]
I'm having an issue where multi file components aren't mounting. I forked this example and moved the JS to its own file and it fails the basic test. Is there a different way to handle multi file components to be compatible with AVA?

https://github.com/Gregoyle/Ava_Vue_Multi_File_Fail
https://github.com/Gregoyle/Ava_Vue_Multi_File_Fail/blob/master/src/components/List.vue

**Comment by eddyerburgh** [comment]
Looks like you've raised an issue in require-extension-hooks-vue — https://github.com/jackmellis/require-extension-hooks-vue/issues/25.

I'm closing, as this is outside the scope of this repo. Thanks for bringing this to my attention though 😀
