### ISSUE TITLE
Demo with Nuxt

### ISSUE THREAD

**Issue by vinayakkulkarni** [eddyerburgh/vue-test-utils-ava-example#5]
Hi,

Just wanted to add a link to the demo repo which uses `Ava` & `Nuxt` for folks coming here via searching the interwebz.

https://github.com/vinayakkulkarni/nuxt-ava-e2e-unit-testing

--
Regards,
Vinayak Ku

**Comment by eddyerburgh** [comment]
Thanks, you can add this to the project README if you'd like

**Comment by vinayakkulkarni** [comment]
@eddyerburgh : I've sent a PR #6. Pl check, review & revert.

Thanks.
